load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "go_default_library",
    srcs = ["listener.go"],
    importpath = "github.com/ghetzel/styx/internal/netutil",
    visibility = ["//github.com/ghetzel/styx:__subpackages__"],
)
